create table student

(

   id integer not null,

   name varchar(255) not null,

   passport_number varchar(255) not null,

   primary key(id)

);

create table role (id integer generated by default as identity, role varchar(255), primary key (id));
create table user (id integer generated by default as identity, active integer, email varchar(255) not null, last_name varchar(255) not null, name varchar(255) not null, primary key (id));